[package]
name = "day11"
version = "0.1.0"
authors = ["Euan Rochester <euan@rochester.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_of_utils = {path="../advent_of_utils"}